#!/usr/bin/env node
/**
 * Compiles the Lucide icons this dashboard uses into CSS mask classes.
 *
 * Why not Lucide's own script: it ships as a browser bundle that walks the DOM
 * and replaces <i data-lucide> elements via innerHTML. That means a second
 * remote script tag and another innerHTML writer, and the dashboard's CSP is
 * script-src 'self' specifically to keep agent-authored output from becoming an
 * injection path. A stylesheet has neither problem.
 *
 * Why masks rather than an inline <symbol> sprite: mask-image + currentColor
 * colours an icon from whatever the surrounding text colour is, in both themes,
 * with no per-icon fill plumbing and no dependence on the sprite living in the
 * same document as the <use>.
 *
 * Adding an icon: put its Lucide name in ICONS and re-run `pnpm build:icons`.
 * The build fails loudly on a name that does not exist rather than silently
 * emitting a blank square.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const guiDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const iconDir = join(guiDir, "node_modules", "lucide-static", "icons");
const outPath = join(guiDir, "styles", "icons.css");

const ICONS = [
  // primary nav + views
  "terminal", "kanban", "calendar-days", "users", "shield-check",
  // utility bar
  "monitor", "user", "sun", "moon", "panel-left", "log-out", "search",
  // agent identity
  "sparkles", "compass", "wrench", "layout-grid", "square-pen",
  "square-check", "book-open", "megaphone", "radar",
  // actions + state
  "plus", "x", "check", "circle-check", "triangle-alert", "activity",
  "arrow-right", "chevron-down", "more-horizontal", "trash-2", "refresh-cw",
  "send-horizontal", "clock", "sliders-horizontal", "bot",
];

const missing = ICONS.filter((name) => !existsSync(join(iconDir, `${name}.svg`)));
if (missing.length) {
  console.error(`build-icons: no such Lucide icon(s): ${missing.join(", ")}`);
  console.error(`  looked in ${iconDir}`);
  process.exit(1);
}

/** Inline SVG in a url() must be percent-escaped for the characters that would end it. */
function dataUri(svg) {
  const compact = svg.replace(/\s*\n\s*/g, " ").replace(/>\s+</g, "><").trim();
  const escaped = compact
    .replace(/%/g, "%25")
    .replace(/#/g, "%23")
    .replace(/</g, "%3C")
    .replace(/>/g, "%3E")
    .replace(/"/g, "'")
    .replace(/\{/g, "%7B")
    .replace(/\}/g, "%7D");
  return `url("data:image/svg+xml,${escaped}")`;
}

const rules = ICONS.map((name) => {
  const uri = dataUri(readFileSync(join(iconDir, `${name}.svg`), "utf-8"));
  return `.i-${name} { --icon-url: ${uri}; }`;
}).join("\n");

const css = `/*
 * GENERATED by mcp/gui/scripts/build-icons.mjs — do not edit.
 * Re-run: pnpm --filter mcp-gui build:icons
 *
 * Usage:  <span class="icon i-kanban" aria-hidden="true"></span>
 * The glyph takes its colour from the surrounding text, so an icon is never
 * hard-coded to one theme.
 */
@layer components {
  .icon[class*="i-"] {
    display: inline-block;
    background-color: currentColor;
    mask-image: var(--icon-url);
    mask-repeat: no-repeat;
    mask-position: center;
    mask-size: contain;
    -webkit-mask-image: var(--icon-url);
    -webkit-mask-repeat: no-repeat;
    -webkit-mask-position: center;
    -webkit-mask-size: contain;
  }

${rules.split("\n").map((l) => `  ${l}`).join("\n")}
}
`;

writeFileSync(outPath, css, "utf-8");
console.log(`build-icons: wrote ${ICONS.length} icons to ${outPath.replace(guiDir + "/", "")}`);
